var _chart=null,_narOrig="";
var CO=["#00e5ff","#00ff88","#ff6b35","#ffd166","#a29bfe","#fd79a8","#55efc4"];

function esc(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function fmtD(v){return String(v||"").replace("T"," ")}
function exL(b,l){if(!b)return"";var m=b.match(new RegExp(l+":\\s*(.+?)(?:\\n|$)","i"));return m?m[1].trim():""}
function pD(p){return p.photoDesc||p.description||exL(p.body,"Description")||"Photo report"}
function pW(p){return p.photoWhere||exL(p.body,"Where")||p.post||""}
function pY(p){return p.photoWhy||exL(p.body,"Why/Purpose")||exL(p.body,"Why")||""}
function pC(p){return p.captureTime||exL(p.body,"Captured")||p.time||""}

function G(){try{var r=localStorage.getItem("opm_config_v2")||localStorage.getItem("tms_config");var c=r?JSON.parse(r):{};if(c&&c.sheetUrl){if(!c.teams||!Array.isArray(c.teams))c.teams=[];return c}return null}catch(e){return null}}

function PU(){var cfg=G()||{};var t=Array.isArray(cfg.teams)?cfg.teams:[];var s=document.getElementById("unit");if(!s)return;var cur=s.value;s.innerHTML='<option value="">ALL UNITS</option>';t.forEach(function(v){var o=document.createElement("option");o.value=v.name;o.textContent=v.name;if(v.name===cur)o.selected=true;s.appendChild(o)})}

function T(){var d=new Date().toISOString().substring(0,10);document.getElementById("from").value=d;document.getElementById("to").value=d;R()}
function W(){var n=new Date(),day=n.getDay();var m=new Date(n);m.setDate(n.getDate()-(day===0?6:day-1));var s=new Date(m);s.setDate(m.getDate()+6);document.getElementById("from").value=m.toISOString().substring(0,10);document.getElementById("to").value=s.toISOString().substring(0,10);R()}

async function Q(){var url=OPM.SHEET_URL();if(!url){try{var r=localStorage.getItem("opm_config_v2")||localStorage.getItem("tms_config");var c=r?JSON.parse(r):{};url=c.sheetUrl||""}catch(e){}}if(!url)return null;var fr=document.getElementById("from").value,to=document.getElementById("to").value;try{var p=new URLSearchParams({action:"getDashboardData",t:Date.now()});if(fr)p.set("dateFrom",fr+" 00:00:00");if(to)p.set("dateTo",to+" 23:59:59");var r=await fetch(url+"?"+p,{cache:"no-store"});return await r.json()}catch(e){return null}}

async function R(){
  PU();var cfg=G();
  if(!cfg){document.getElementById("content").innerHTML='<div class="card"><div class="card-body empty">No backend configured. Open Admin page and save settings first.</div></div>';return}
  OPM.saveConfig(cfg);if(_chart){_chart.destroy();_chart=null}
  document.getElementById("content").innerHTML='<div class="card"><div class="card-body empty">Loading report...</div></div>';
  var data=await Q();
  var su=document.getElementById("unit").value||"ALL UNITS",df=document.getElementById("from").value||"beginning",dt=document.getElementById("to").value||"present";
  var c2=OPM.getConfig();
  document.getElementById("cover-title").textContent=(c2.eventName||"TERMINAL OPERATIONS AND MANAGEMENT REPORT");
  document.getElementById("cover-sub").textContent=(c2.location||"BROOKE'S POINT GRAND TERMINAL");
  if(!data||!data.summary||(data.summary.totalMessages===0&&data.summary.totalPersonnel===0)){
    document.getElementById("content").innerHTML='<div class="card"><div class="card-body empty">No data for '+esc(su)+' from '+esc(df)+' to '+esc(dt)+'<br><br><button class="btn btn-sm" onclick="T()">TODAY</button> <button class="btn btn-sm" onclick="R()">ALL TIME</button></div></div>';return
  }
  B(data,su,df,dt)
}

function B(data,su,df,dt){
  var s=data.summary;var ud=Array.isArray(data.unitData)?data.unitData:[];var photos=data.photos||[];var all=data.allMessages||[];var pt=data.personnelByTeam||{};
  if(su!=="ALL UNITS"){ud=ud.filter(function(u){return u.team===su});photos=photos.filter(function(p){return p.team===su});all=all.filter(function(m){return m.team===su});var fp={};if(pt[su])fp[su]=pt[su];pt=fp}
  var tm=ud.reduce(function(a,u){return a+(u.messages||0)},0),tt=ud.reduce(function(a,u){return a+(u.tasks||0)},0),ti=ud.reduce(function(a,u){return a+(u.incidents||0)},0),tp=ud.reduce(function(a,u){return a+(u.photos||0)},0);
  var un=ud.map(function(u){return u.team}),ut=ud.map(function(u){return u.tasks||0}),up=ud.map(function(u){return u.photos||0});
  var pers=(su!=="ALL UNITS"?(pt[su]||0):s.totalPersonnel),actv=(su!=="ALL UNITS"?(pt[su]||0):s.onlineNow);

  var h="";
  h+=C("EXECUTIVE SUMMARY","",S(tm,tt,tp,ti,pers,actv));
  if(un.length>0){h+=C("UNIT PERFORMANCE","PERIOD: "+esc(df)+" "+esc(dt),UT(ud,un))}
  if(photos.length>0){h+=PG(photos,un,su,df,dt)}
  var insp=all.filter(function(m){return m.type==="inspection"});
  if(insp.length>0){h+=IR(insp,df,su,dt)}
  var nar="PERIOD: "+df+" to "+dt+" | UNIT: "+su+"\n\nDuring this period, "+tm+" communications were recorded. "+tt+" tasks accomplished, "+tp+" photo reports submitted, and "+ti+" incidents logged.\n\nGenerated by OPM on "+OPM.formatDateTime()+".";
  h+=C("NARRATIVE","EDITABLE",'<textarea class="narrative-box" id="nar-text">'+esc(nar)+'</textarea><div class="flex gap-sm" style="margin-top:10px"><button class="btn btn-success btn-sm" onclick="SN()">SAVE</button><button class="btn btn-sm" onclick="RN()">RESET</button><span id="nar-ok" style="display:none;font-family:var(--font-mono);font-size:10px;color:var(--success)">SAVED</span></div>');
  // Comms log removed from report
  h+=SIG(su);
  h+=PF();
  document.getElementById("content").innerHTML=h;

  if(un.length>0){setTimeout(function(){var cv=document.getElementById("chart");if(cv){_chart=new Chart(cv,{type:"bar",data:{labels:un,datasets:[{label:"Photos",data:up,backgroundColor:CO.slice(0,un.length),borderWidth:0,borderRadius:3},{label:"Tasks",data:ut,backgroundColor:CO.slice(0,un.length).map(function(x){return x+"44"}),borderWidth:0,borderRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#6a80b0",font:{family:"Share Tech Mono",size:10}}}},scales:{x:{ticks:{color:"#6a80b0",font:{size:9},maxRotation:45},grid:{color:"#1e326020"}},y:{ticks:{color:"#6a80b0",font:{size:9}},grid:{color:"#1e326030"},beginAtZero:true}}}})}},300)}
  var nt=document.getElementById("nar-text");if(nt){_narOrig=nt.value;var key="nar_"+su.replace(/[^a-z0-9]/gi,"_")+"_"+(df||"any")+"_"+(dt||"any");var c3=OPM.getConfig();if(c3&&c3[key])nt.value=c3[key]}
}

function C(hdr,sub,body){return'<div class="card"><div class="card-hdr">'+hdr+" "+sub+'</div><div class="card-body">'+body+'</div></div>'}
function S(m,tt,tp,ti,p,a){return'<div class="stats"><div><div class="n">'+m+'</div><div class="l">Messages</div></div><div><div class="n" style="color:var(--success)">'+tt+'</div><div class="l">Tasks</div></div><div><div class="n">'+tp+'</div><div class="l">Photos</div></div><div><div class="n" style="color:var(--warning)">'+ti+'</div><div class="l">Incidents</div></div><div><div class="n">'+p+'</div><div class="l">Personnel</div></div><div><div class="n" style="color:var(--success)">'+a+'</div><div class="l">Online</div></div></div>'}

function UT(ud,un){var h='<table><tr><th></th><th>UNIT</th><th class="num">PHOTOS</th><th class="num">TASKS</th><th class="num">INC</th><th class="num">COMMS</th></tr>';ud.forEach(function(u,i){h+='<tr><td><span class="dot" style="background:'+CO[i%7]+'"></span></td><td><strong>'+esc(u.team)+'</strong></td><td class="num">'+(u.photos||0)+'</td><td class="num" style="color:var(--success)">'+(u.tasks||0)+'</td><td class="num" style="color:'+((u.incidents||0)>0?"var(--warning)":"var(--text-dim)")+'">'+(u.incidents||0)+'</td><td class="num">'+(u.messages||0)+'</td></tr>'});h+='</table><div style="margin-top:14px;height:200px"><canvas id="chart"></canvas></div>';return h}

// ── Editable photo store ──
function phKey(p){return "phed_"+((p.url||"")+(p.time||"")+(p.sender||"")).replace(/[^a-z0-9]/gi,"").substring(0,40)}
function getPhEdits(p){try{return JSON.parse(localStorage.getItem(phKey(p))||"{}")}catch(e){return{}}}
function savePhEdits(p,ed){localStorage.setItem(phKey(p),JSON.stringify(ed))}

// ── Photo include/exclude store ──
function phiKey(su,df,dt){return "phi_"+su.replace(/[^a-z0-9]/gi,"_")+"_"+(df||"")+"_"+(dt||"")}
function getPhIncludes(su,df,dt){try{return JSON.parse(localStorage.getItem(phiKey(su,df,dt))||"{}")}catch(e){return{}}}
function savePhIncludes(su,df,dt,obj){localStorage.setItem(phiKey(su,df,dt),JSON.stringify(obj))}

function PG(photos,un,su,df,dt){
  var sorted = [].concat(photos).sort(function(a,b){
    var ta = (a.captureTime||a.time||'').toString();
    var tb = (b.captureTime||b.time||'').toString();
    return tb.localeCompare(ta);
  });
  var grouped = {};
  sorted.forEach(function(p){
    var u = p.team||'UNASSIGNED';
    if(!grouped[u]) grouped[u] = [];
    grouped[u].push(p);
  });
  var unitOrder = Object.keys(grouped).sort();
  var total = photos.length;
  // Build unique photo IDs and restore include state
  var allIds=[];
  sorted.forEach(function(p){allIds.push(phKey(p))});
  var inclState=getPhIncludes(su,df,dt);
  // Auto-include all if no saved state
  if(Object.keys(inclState).length===0){allIds.forEach(function(id){inclState[id]=true});savePhIncludes(su,df,dt,inclState)}

  var h = '<div class="card photo-report-card"><div class="card-hdr">PHOTO REPORTS ('+total+')';
  h += '<span style="display:flex;gap:8px;align-items:center">';
  h += '<button class="btn btn-sm" onclick="selAllPhotos(true,\''+esc(su)+'\',\''+esc(df)+'\',\''+esc(dt)+'\')">SEL ALL</button>';
  h += '<button class="btn btn-sm" onclick="selAllPhotos(false,\''+esc(su)+'\',\''+esc(df)+'\',\''+esc(dt)+'\')">SEL NONE</button>';
  h += '</span>';
  h += '</div><div class="card-body">';

  unitOrder.forEach(function(unit){
    var up = grouped[unit];
    var uc = CO[un.indexOf(unit)%7]||'var(--accent)';
    h += '<div style="margin-bottom:16px;border-bottom:2px solid '+uc+';padding-bottom:6px;">';
    h += '<h3 style="font-family:var(--font-mono);font-size:11px;color:'+uc+';letter-spacing:1px;margin-bottom:6px;">'+esc(unit)+' ('+up.length+' reports)</h3>';
    h += '<div class="photo-grid">';
    up.forEach(function(p,i){
      var m2 = (p.url||'').match(/[?&]id=([a-zA-Z0-9_-]+)/);
      var e = m2 ? ('https://lh3.googleusercontent.com/d/'+m2[1]) : p.url;
      var desc = pD(p), where = pW(p), why = pY(p), cap = pC(p);
      var pk=phKey(p);
      var ed=getPhEdits(p);
      var incl=inclState[pk]!==false; // default true
      h += '<div class="photo-card" id="pc_'+pk+'">';
      h += '<div class="photo-side" data-url="'+esc(p.url)+'" style="cursor:pointer">';
      h += '<img src="'+esc(e)+'" loading="lazy">';
      h += '<span class="pb" style="background:'+uc+'">'+esc(p.team||'')+'</span>';
      h += '<span class="pn">';
      h += '<input type="checkbox" class="photo-include-chk" data-id="'+esc(pk)+'" '+(incl?'checked':'')+' onchange="togglePhotoInclude(this,\''+esc(pk)+'\',\''+esc(su)+'\',\''+esc(df)+'\',\''+esc(dt)+'\')" title="Include in print/export">';
      h += ' #'+(i+1)+'</span>';
      h += '</div>';
      h += '<div class="info-side">';
      // Editable fields
      h += '<div class="fn" contenteditable="true" data-field="desc" data-pk="'+esc(pk)+'" onblur="savePhotoField(this)">'+esc(ed.desc||desc)+'</div>';
      h += '<div class="fr">';
      var wv=ed.where||where;
      h += '<span class="fk">Location</span><span class="fv" contenteditable="true" data-field="where" data-pk="'+esc(pk)+'" onblur="savePhotoField(this)">'+esc(wv)+'</span>';
      var cv=ed.cap||cap;
      h += '<span class="fk">Captured</span><span class="fv" contenteditable="true" data-field="cap" data-pk="'+esc(pk)+'" onblur="savePhotoField(this)">'+esc(fmtD(cv))+'</span>';
      h += '<span class="fk">Unit</span><span class="fv" style="color:'+uc+';font-weight:600">'+esc(p.team||'')+'</span>';
      h += '<span class="fk">By</span><span class="fv">'+esc(p.sender||'')+'</span>';
      h += '</div>';
      var yv=ed.why||why;
      if(yv) h += '<div class="fp" contenteditable="true" data-field="why" data-pk="'+esc(pk)+'" onblur="savePhotoField(this)">"'+esc(yv)+'"</div>';
      h += '</div></div>';
    });
    h += '</div></div>';
  });
  h += '</div></div>';
  return h;
}

function selAllPhotos(on,su,df,dt){
  var st=getPhIncludes(su,df,dt);
  var chks=document.querySelectorAll('.photo-include-chk');
  chks.forEach(function(cb){
    cb.checked=on;
    st[cb.getAttribute('data-id')]=on;
  });
  savePhIncludes(su,df,dt,st);
}

function togglePhotoInclude(cb,pk,su,df,dt){
  var st=getPhIncludes(su,df,dt);
  st[pk]=cb.checked;
  savePhIncludes(su,df,dt,st);
}

function savePhotoField(el){
  var pk=el.getAttribute('data-pk');
  var field=el.getAttribute('data-field');
  var val=el.textContent.trim();
  var ed=getPhEdits({url:pk});
  ed[field]=val;
  savePhEdits({url:pk},ed);
}

// ── INSPECTION REPORT — Table format ──
function IR(insp,df,su,dt){
  var CK="\u2713";
  // Collect all items across all inspections: {label -> {count, sections, photos:[], inspectors:[], remarks:[]}}
  var items={};
  insp.forEach(function(ins){
    var inspector=ins.sender||"";
    var team=ins.team||"";
    var pm={};
    try{var pd=JSON.parse(ins.photo||"[]");if(Array.isArray(pd))pd.forEach(function(p){pm[p.label]=(p.urls||[]).map(function(u){var m2=(u||"").match(/[?&]id=([a-zA-Z0-9_-]+)/);return{embed:m2?"https://lh3.googleusercontent.com/d/"+m2[1]:u,raw:u}})})}catch(e){}
    var ls=(ins.body||"").split("\n");
    var insRemarks="";
    ls.forEach(function(l){
      if(l.indexOf("Remarks: ")!==-1)insRemarks=l.substring(9).trim();
      if(l.indexOf(CK+" ")!==-1){
        var cl=l.replace(CK+" ","").trim();
        var lb=cl.replace(/ \(.*\)$/,"");
        var se="";var m3=cl.match(/\((.+)\)$/);if(m3)se=m3[1];if(!se)se="General";
        if(!items[lb])items[lb]={count:0,sections:[],photos:[],inspectors:[],remarks:[]};
        items[lb].count++;
        if(items[lb].sections.indexOf(se)<0)items[lb].sections.push(se);
        if(pm[lb])pm[lb].forEach(function(ph){items[lb].photos.push(ph)});
        if(items[lb].inspectors.indexOf(inspector)<0)items[lb].inspectors.push(inspector);
        if(insRemarks&&items[lb].remarks.indexOf(insRemarks)<0)items[lb].remarks.push(insRemarks);
      }
    });
  });

  var itemKeys=Object.keys(items).sort();
  if(itemKeys.length===0)return '<div class="card"><div class="card-hdr">DAILY INSPECTION REPORT</div><div class="card-body empty">No checklist items found.</div></div>';

  var h='<div class="card inspect-table-card"><div class="card-hdr">DAILY INSPECTION REPORT — '+insp.length+' inspection'+(insp.length>1?'s':'')+' by '+(new Set(insp.map(function(x){return x.sender}))).size+' inspector(s)</div><div class="card-body">';
  h+='<table class="inspect-tbl"><thead><tr>';
  h+='<th style="width:5%">#</th>';
  h+='<th style="width:25%">CHECKLIST ITEM</th>';
  h+='<th style="width:7%">TIMES INSPECTED</th>';
  h+='<th style="width:18%">REMARKS / OBSERVATIONS</th>';
  h+='<th style="width:25%">PHOTOS</th>';
  h+='<th style="width:20%">INSPECTED BY</th>';
  h+='</tr></thead><tbody>';

  itemKeys.forEach(function(lb,i){
    var it=items[lb];
    // Deduplicate photos by embed URL
    var seen={};var uniq=[];
    it.photos.forEach(function(ph){if(!seen[ph.embed]){seen[ph.embed]=true;uniq.push(ph)}});
    // Inspectors names (may be multiple)
    var insNames=it.inspectors.join(", ");
    // Remarks key for saving edits
    var rk="irm_"+lb.replace(/[^a-z0-9]/gi,"_").substring(0,50)+"_"+(su||"ALL").replace(/[^a-z0-9]/gi,"_")+"_"+(df||"")+"_"+(dt||"");
    var savedRemark=localStorage.getItem(rk)||"";
    var remarkVal=savedRemark||it.remarks.join("; ");
    h+='<tr>';
    h+='<td class="num">'+(i+1)+'</td>';
    h+='<td><strong>'+esc(lb)+'</strong><div style="font-size:8px;color:var(--text-dim);margin-top:2px">'+esc(it.sections.join(", "))+'</div></td>';
    h+='<td class="num" style="font-family:var(--font-mono);font-weight:700;font-size:16px;color:var(--accent)">'+it.count+'</td>';
    h+='<td><div class="inspect-remark-cell" contenteditable="true" data-rk="'+esc(rk)+'" onblur="saveInspectRemark(this)" style="font-size:12px;min-height:40px;line-height:1.5">'+esc(remarkVal)+'</div></td>';
    h+='<td><div class="inspect-photos">';
    uniq.slice(0,6).forEach(function(ph){h+='<img src="'+esc(ph.embed)+'" data-url="'+esc(ph.raw)+'" loading="lazy" style="width:70px;height:52px;object-fit:cover;border-radius:3px;border:1px solid var(--border-color);cursor:pointer">'});
    if(uniq.length>6)h+='<span style="font-size:9px;color:var(--text-dim);font-family:var(--font-mono)">+'+ (uniq.length-6)+' more</span>';
    h+='</div></td>';
    h+='<td><span style="font-size:12px;font-weight:600;color:var(--text-secondary)">'+esc(insNames)+'</span></td>';
    h+='</tr>';
  });

  h+='</tbody></table>';
  // Summary
  h+='<div style="margin-top:12px;padding:14px 16px;background:var(--accent-dim);border-radius:6px;border:1px solid var(--border-color)"><strong>INSPECTION SUMMARY:</strong> '+insp.length+' inspection(s) conducted covering '+itemKeys.length+' unique checklist items. '+(new Set(insp.map(function(x){return x.sender}))).size+' inspector(s) participated. All items found satisfactory.</div>';
  h+='</div></div>';
  return h;
}

function saveInspectRemark(el){
  var rk=el.getAttribute('data-rk');
  localStorage.setItem(rk,el.textContent.trim());
}

// ── Comms log (kept but not called by default) ──
function CL(all){var h='<div class="card"><div class="card-hdr">COMMUNICATIONS LOG ('+all.length+')</div><div class="card-body"><div class="msg-log">';all.slice().reverse().slice(0,80).forEach(function(m){h+='<div class="mr"><span class="mt">'+esc((m.time||"").substring(0,19))+'</span><span class="ms">'+esc(m.sender||"")+(m.team?" ["+esc(m.team)+"]":"")+'</span><span class="mb">'+esc((m.body||"").substring(0,130))+(m.photo?" [photo]":"")+'</span></div>'});h+='</div></div></div>';return h}

function HU(n){var u=(n||"").toUpperCase();if(u.indexOf("UTILITY")>=0||u.indexOf("MAINTENANCE")>=0)return{name:"ALONSO S. PERALTA",title:"Utility &amp; Maintenance Unit Head"};if(u.indexOf("OPERATIONS")>=0)return{name:"JOSHIEL D. BELEN",title:"Operations Unit Head"};if(u.indexOf("ADMIN")>=0)return{name:"CRISTIAN VICERA",title:"Administrative Unit Head"};if(u.indexOf("SAFETY")>=0||u.indexOf("SECURITY")>=0)return{name:"CRISTIAN VICERA",title:"Administrative Unit Head"};if(u.indexOf("TASK FORCE")>=0||u.indexOf("BPGT TASK")>=0)return{name:"JOSHIEL D. BELEN",title:"Operations Unit Head"};return null}
function SIG(su){
  var h='<div class="card sig-block"><div class="card-hdr">SIGNATURES</div><div class="card-body">';
  h+='<div class="sig-section"><div class="sig-label">Prepared by:</div><div class="sig-line"></div><div class="sig-name" style="font-size:12px;text-align:center;margin-top:4px">JULAIDA U. KENTONG / CRISTINE MAE A. JONTILANO</div><div class="sig-hint">Signature over Printed Name / Date</div></div>';
  if(su==="ALL UNITS"){
    h+='<div class="sig-section"><div class="sig-label">Reviewed by:</div>';
    h+='<div class="sig-row-3">';
    h+='<div class="sig-col"><div class="sig-line"></div><div class="sig-name">ALONSO S. PERALTA</div><div class="sig-title">Utility &amp; Maintenance Unit Head</div></div>';
    h+='<div class="sig-col"><div class="sig-line"></div><div class="sig-name">JOSHIEL D. BELEN</div><div class="sig-title">Operations Unit Head</div></div>';
    h+='<div class="sig-col"><div class="sig-line"></div><div class="sig-name">CRISTIAN VICERA</div><div class="sig-title">Administrative Unit Head</div></div>';
    h+='</div>';
    h+='</div>';
  }else{var hd=HU(su);if(hd){h+='<div class="sig-section"><div class="sig-label">Reviewed by:</div><div class="sig-row-1"><div class="sig-col"><div class="sig-line"></div><div class="sig-name">'+hd.name+'</div><div class="sig-title">'+hd.title+'</div></div></div></div>'}}
  h+='<div class="sig-row-2">';
  h+='<div class="sig-col"><div class="sig-label">Noted by:</div><div class="sig-line"></div><div class="sig-name">JOEY SABENACIO HEREDERO</div><div class="sig-title">BPGT Administrator</div></div>';
  h+='<div class="sig-col"><div class="sig-label">Approved by:</div><div class="sig-line"></div><div class="sig-name">EDGAR P. LACANDAZO</div><div class="sig-title">Municipal Administrator</div></div>';
  h+='</div>';
  h+='</div></div>';
  return h;
}
function PF(){return'<div class="print-footer"><img src="icon-192.png" style="width:28px;height:28px;border-radius:50%"><span class="pf-t">-=pagong=-</span><span class="pf-s">JOEY SABENACIO HEREDERO &middot; OPM &middot; &copy; 2026</span></div>'}

function SN(){var nt=document.getElementById("nar-text");if(!nt)return;var su2=document.getElementById("unit").value||"ALL UNITS",df2=document.getElementById("from").value||"any",dt2=document.getElementById("to").value||"any";var c4=OPM.getConfig();if(!c4)c4={};c4["nar_"+su2.replace(/[^a-z0-9]/gi,"_")+"_"+df2+"_"+dt2]=nt.value.trim();OPM.saveConfig(c4);var ok=document.getElementById("nar-ok");if(ok){ok.style.display="inline";setTimeout(function(){ok.style.display="none"},2000)}}
function RN(){if(_narOrig)document.getElementById("nar-text").value=_narOrig}

// Click handler for photo cards
document.addEventListener("click",function(e){
  // Skip clicks on checkboxes, contenteditable, buttons
  if(e.target.closest('input[type="checkbox"]')||e.target.closest('[contenteditable]')||e.target.closest('button')||e.target.closest('.btn'))return;
  var el=e.target.closest("[data-url]");
  if(el){
    var url=el.getAttribute("data-url");
    if(url)window.open(url);
  }
});

document.addEventListener("DOMContentLoaded",function(){PU();var cfg=G();if(!cfg){document.getElementById("content").innerHTML='<div class="card"><div class="card-body empty">No backend configured. Open Admin page and save settings first.</div></div>';return}setTimeout(function(){T()},300)});

// Print handler: hide unchecked photos before printing, restore after
window.addEventListener("beforeprint",function(){
  document.querySelectorAll('.photo-include-chk:not(:checked)').forEach(function(cb){
    var pc=cb.closest('.photo-card');
    if(pc)pc.style.display='none';
  });
  document.querySelectorAll('.photo-include-chk').forEach(function(cb){
    cb.style.display='none';
  });
});
window.addEventListener("afterprint",function(){
  document.querySelectorAll('.photo-card').forEach(function(pc){
    pc.style.display='';
  });
  document.querySelectorAll('.photo-include-chk').forEach(function(cb){
    cb.style.display='';
  });
});
